"""Adversarial and diagnostic test suite for Survival Model Explainability (LOOP 10).

Verifies all 18 non-negotiable mathematical, scientific, and governance invariants:
1. Sum of feature contributions equals linear predictor.
2. exp(linear_predictor) equals relative hazard.
3. No future features are used.
4. No EVAL outcome is used.
5. Explanation uses exact snapshot features.
6. Missing values are handled consistently.
7. Categorical explanations map correctly.
8. Positive contribution is classified correctly.
9. Negative contribution is classified correctly.
10. Top contributors are deterministic.
11. Artifact save/load preserves explanations.
12. Model hash/version is preserved.
13. Transition isolation works.
14. Citizen projection strips internal ML fields.
15. Officer projection retains permitted analytical fields.
16. Uncertainty warnings are preserved.
17. Extrapolation warnings are preserved.
18. No causal language is generated by the explanation engine.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import pytest

from calibration.survival_calibration import (
    BANNED_CITIZEN_FIELDS,
    GOVERNANCE_SAFETY_DISCLAIMER,
    MODEL_VERSION,
    PURGED_LEAKAGE_FEATURES,
    UncertaintyStatus,
)
from evaluation.survival_evaluation import load_trained_cox_models
from explainability.survival_explainability import (
    FEATURE_VERSION,
    ContributionDirection,
    SnapshotExplanation,
    SurvivalExplainer,
    load_survival_explainer,
    run_full_survival_explainability,
)

API_ROOT = Path(__file__).resolve().parents[2]
GIT_ROOT = Path(__file__).resolve().parents[5]
CLEAN_DATA_DIR = GIT_ROOT / "data" / "real_data" / "clean"
MODELS_DIR = GIT_ROOT / "models" / "cox_baseline"


@pytest.fixture(scope="module")
def train_features() -> pd.DataFrame:
    """Load clean TRAIN features."""
    p = CLEAN_DATA_DIR / "survival_train_features.csv"
    assert p.exists()
    return pd.read_csv(p)


@pytest.fixture(scope="module")
def eval_features() -> pd.DataFrame:
    """Load clean EVAL holdout features."""
    p = CLEAN_DATA_DIR / "survival_eval_features.csv"
    assert p.exists()
    return pd.read_csv(p)


@pytest.fixture(scope="module")
def explainer() -> SurvivalExplainer:
    """Initialize standard SurvivalExplainer."""
    return load_survival_explainer(MODELS_DIR, CLEAN_DATA_DIR)


# --- INVARIANT 1: ADDITIVE DECOMPOSITION TO LINEAR PREDICTOR ---

def test_sum_of_feature_contributions_equals_linear_predictor(train_features, explainer):
    """Invariant 1: Sum of beta_j * x_j must exactly equal the linear predictor."""
    sample = train_features.iloc[:30]
    for _, row in sample.iterrows():
        expl = explainer.explain_snapshot(row)
        sum_contribs = sum(c.contribution for c in expl.all_contributions)
        assert abs(sum_contribs - expl.linear_predictor) < 1e-5, (
            f"Sum mismatch: {sum_contribs} != {expl.linear_predictor}"
        )


# --- INVARIANT 2: MULTIPLICATIVE HAZARD MULTIPLIER ---

def test_exp_linear_predictor_equals_relative_hazard(train_features, explainer):
    """Invariant 2: exp(linear_predictor) and prod(hazard_multipliers) must equal relative_hazard."""
    sample = train_features.iloc[:30]
    for _, row in sample.iterrows():
        expl = explainer.explain_snapshot(row)
        expected_hazard = float(np.exp(expl.linear_predictor))
        assert abs(expl.relative_hazard - expected_hazard) < 1e-5, (
            f"Relative hazard mismatch: {expl.relative_hazard} != {expected_hazard}"
        )
        prod_mults = float(np.prod([c.hazard_multiplier for c in expl.all_contributions]))
        assert abs(prod_mults - expl.relative_hazard) < 1e-4, (
            f"Multiplier product mismatch: {prod_mults} != {expl.relative_hazard}"
        )


# --- INVARIANT 3 & 4: FEATURE & OUTCOME LEAKAGE GUARDS ---

def test_no_future_features_used(train_features, explainer):
    """Invariant 3: Purged future features must be strictly rejected."""
    tainted = train_features.iloc[0].to_dict()
    tainted["award_recorded"] = True
    with pytest.raises(ValueError, match="Feature leakage violation"):
        explainer.explain_snapshot(tainted)


def test_no_eval_outcomes_used(eval_features, explainer):
    """Invariant 4: Explanations must be generated without reference to EVAL event targets."""
    # Ensure no target columns exist in input features
    assert "event_observed" not in eval_features.columns
    assert "duration_at_risk_days" not in eval_features.columns

    # Generating explanations for EVAL snapshots must succeed with feature inputs only
    eval_expls = explainer.explain_dataframe(eval_features.iloc[:20])
    assert len(eval_expls) == 20
    for e in eval_expls:
        assert e.relative_hazard > 0


# --- INVARIANT 5: POINT-IN-TIME FEATURE FIDELITY ---

def test_explanation_uses_exact_snapshot_features(train_features, explainer):
    """Invariant 5: Feature values in explanation must match input snapshot values exactly."""
    row = train_features.iloc[5]
    expl = explainer.explain_snapshot(row)
    for c in expl.all_contributions:
        if c.feature_name in row and not pd.isna(row[c.feature_name]):
            if isinstance(row[c.feature_name], (int, float)):
                assert abs(float(c.raw_value) - float(row[c.feature_name])) < 1e-5


# --- INVARIANT 6: MISSING VALUE HANDLING ---

def test_missing_values_handled_consistently(train_features, explainer):
    """Invariant 6: Missing features are explicitly flagged and tracked."""
    row = train_features.iloc[0].to_dict()
    row["derived_notice_count"] = np.nan
    expl = explainer.explain_snapshot(row)
    missing_names = [m.feature_name for m in expl.missing_features]
    assert "derived_notice_count" in missing_names
    for m in expl.missing_features:
        assert m.was_missing is True
        assert m.imputation_applied == "zero_or_baseline_imputation"


# --- INVARIANT 7: CATEGORICAL FEATURE MAPPING ---

def test_categorical_explanations_map_correctly(train_features, explainer):
    """Invariant 7: One-hot encoded features map to human-readable interpretations."""
    sample = train_features[train_features["transition"] == "CASE_INITIATION_TO_MILESTONE"].iloc[0]
    expl = explainer.explain_snapshot(sample)
    for c in expl.all_contributions:
        assert c.human_readable_name != ""
        assert not c.human_readable_name.startswith("current_stage_")
        assert not c.human_readable_name.startswith("district_")


# --- INVARIANT 8 & 9: CONTRIBUTION DIRECTION CLASSIFICATION ---

def test_positive_contribution_classified_correctly(train_features, explainer):
    """Invariant 8: Positive beta * x must be classified as INCREASED_HAZARD."""
    sample = train_features.iloc[:20]
    for _, row in sample.iterrows():
        expl = explainer.explain_snapshot(row)
        for c in expl.all_contributions:
            if c.contribution > 1e-6:
                assert c.direction == ContributionDirection.INCREASED_HAZARD.value
                assert c.hazard_multiplier > 1.0


def test_negative_contribution_classified_correctly(train_features, explainer):
    """Invariant 9: Negative beta * x must be classified as DECREASED_HAZARD."""
    sample = train_features.iloc[:20]
    for _, row in sample.iterrows():
        expl = explainer.explain_snapshot(row)
        for c in expl.all_contributions:
            if c.contribution < -1e-6:
                assert c.direction == ContributionDirection.DECREASED_HAZARD.value
                assert c.hazard_multiplier < 1.0


# --- INVARIANT 10: DETERMINISTIC EXPLANATIONS ---

def test_top_contributors_deterministic(train_features, explainer):
    """Invariant 10: Repeated explanation calls on same input yield identical top contributors."""
    row = train_features.iloc[10]
    expl_1 = explainer.explain_snapshot(row, prediction_timestamp="2026-09-30T00:00:00Z")
    expl_2 = explainer.explain_snapshot(row, prediction_timestamp="2026-09-30T00:00:00Z")

    assert expl_1.linear_predictor == expl_2.linear_predictor
    assert expl_1.relative_hazard == expl_2.relative_hazard
    assert len(expl_1.top_positive_contributors) == len(expl_2.top_positive_contributors)
    assert len(expl_1.top_negative_contributors) == len(expl_2.top_negative_contributors)
    for c1, c2 in zip(expl_1.top_positive_contributors, expl_2.top_positive_contributors):
        assert c1.feature_name == c2.feature_name
        assert c1.contribution == c2.contribution


# --- INVARIANT 11: ARTIFACT SAVE AND LOAD ---

def test_artifact_save_load_preserves_explanations(tmp_path, train_features, explainer):
    """Invariant 11: Explanation artifacts serialize to JSON and CSV with complete preservation."""
    sample = train_features.iloc[:10]
    expls = explainer.explain_dataframe(sample)
    from explainability.survival_explainability import save_explanation_artifacts
    saved = save_explanation_artifacts(expls, tmp_path)

    assert saved["explanations_json"].exists()
    assert saved["explanations_csv"].exists()

    with open(saved["explanations_json"]) as f:
        loaded_json = json.load(f)
    assert len(loaded_json) == 10
    assert loaded_json[0]["case_id"] == expls[0].case_id
    assert loaded_json[0]["linear_predictor"] == expls[0].linear_predictor


# --- INVARIANT 12: MODEL HASH AND VERSION TRACKING ---

def test_model_hash_and_version_preserved(train_features, explainer):
    """Invariant 12: Model version and coefficient checksum are explicitly attached."""
    row = train_features.iloc[0]
    expl = explainer.explain_snapshot(row)
    assert expl.model_version == MODEL_VERSION
    assert expl.feature_version == FEATURE_VERSION
    assert len(expl.model_checksum) == 16


# --- INVARIANT 13: TRANSITION ISOLATION ---

def test_transition_isolation(train_features, explainer):
    """Invariant 13: Explanations strictly isolate features by transition."""
    for trans in ["SECTION_11_TO_SECTION_19", "SECTION_19_TO_AWARD", "CASE_INITIATION_TO_MILESTONE"]:
        sub = train_features[train_features["transition"] == trans]
        expl = explainer.explain_snapshot(sub.iloc[0])
        assert expl.transition == trans
        if trans == "SECTION_11_TO_SECTION_19":
            assert len(expl.all_contributions) == 3
        elif trans == "SECTION_19_TO_AWARD":
            assert len(expl.all_contributions) == 8
        elif trans == "CASE_INITIATION_TO_MILESTONE":
            assert len(expl.all_contributions) == 14


# --- INVARIANT 14: CITIZEN VIEW FIELD SUPPRESSION ---

def test_citizen_projection_strips_internal_ml_fields(train_features, explainer):
    """Invariant 14: Citizen explanation view strips all 7 banned internal fields."""
    row = train_features.iloc[0]
    expl = explainer.explain_snapshot(row)
    cit_view = explainer.to_citizen_view(expl, current_stage="SECTION_11", days_in_stage=60)
    cit_dict = cit_view.__dict__

    for banned in BANNED_CITIZEN_FIELDS:
        assert banned not in cit_dict, f"Security violation: banned field {banned} found in citizen view"

    # Confirms citizen view includes human-readable statutory guidance
    assert cit_view.current_stage == "SECTION_11"
    assert "RFCTLARR 2013" in cit_view.statutory_rights_summary


# --- INVARIANT 15: OFFICER VIEW COMPLETENESS ---

def test_officer_projection_retains_permitted_analytical_fields(train_features, explainer):
    """Invariant 15: Officer explanation view retains permitted analytical telemetry."""
    row = train_features.iloc[0]
    expl = explainer.explain_snapshot(row)
    off_view = explainer.to_officer_view(expl)

    assert hasattr(off_view, "relative_hazard")
    assert hasattr(off_view, "linear_predictor")
    assert hasattr(off_view, "why_hazard_is_higher")
    assert hasattr(off_view, "why_hazard_is_lower")
    assert off_view.governance_disclaimer == GOVERNANCE_SAFETY_DISCLAIMER


# --- INVARIANT 16 & 17: UNCERTAINTY & EXTRAPOLATION WARNINGS ---

def test_uncertainty_warnings_preserved(train_features, explainer):
    """Invariant 16: Uncertainty status correctly reflects small-event regimes."""
    s19_row = train_features[train_features["transition"] == "SECTION_19_TO_AWARD"].iloc[0]
    expl = explainer.explain_snapshot(s19_row)
    assert expl.uncertainty_status == UncertaintyStatus.EXTREME_UNCERTAINTY_ZERO_EVENTS.value
    assert "CRITICAL" in expl.data_quality_warning


def test_extrapolation_warnings_preserved(train_features, explainer):
    """Invariant 17: Horizons > 148d are flagged as extrapolated relative to holdout follow-up."""
    row = train_features.iloc[0]
    expl = explainer.explain_snapshot(row)
    assert expl.extrapolation_status["30d"] is False
    assert expl.extrapolation_status["90d"] is False
    assert expl.extrapolation_status["180d"] is True
    assert expl.extrapolation_status["365d"] is True
    assert expl.extrapolation_status["730d"] is True


# --- INVARIANT 18: NO CAUSAL LANGUAGE ---

def test_no_causal_language_in_explanation_engine(train_features, explainer):
    """Invariant 18: Explanations must strictly use associative, non-causal phrasing."""
    banned_words = ["caused", "causation", "responsible for delay", "caused the delay", "caused progress"]
    sample = train_features.iloc[:20]
    for _, row in sample.iterrows():
        expl = explainer.explain_snapshot(row)
        for c in expl.all_contributions:
            narrative_lower = c.explanation_narrative.lower()
            for bw in banned_words:
                assert bw not in narrative_lower, f"Causal violation: found '{bw}' in '{c.explanation_narrative}'"
        off_view = explainer.to_officer_view(expl)
        summary_lower = off_view.summary_narrative.lower()
        for bw in banned_words:
            assert bw not in summary_lower, f"Causal violation in summary: found '{bw}'"
